package com.example.backend.types;

public enum SPECIALITY_TYPE {
    GENERAL_PHYSICIAN,
    ENT_SPECIALIST,
    OPHTHALMOLOGIST,
    DENTIST,
    DERMATOLOGIST,
    IMMUNOLOGIST,
    CARDIOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    ORTHOPEDIST,
    UROLOGIST,
    GYNAECOLOGIST
}
